name: PlatformIO CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Create config.h
        run: |
          cp "${GITHUB_WORKSPACE}/noisemeter-device/config.h.example" "${GITHUB_WORKSPACE}/noisemeter-device/config.h"

      - name: Build PlatformIO Project (esp32-pcb)
        run: pio run -e esp32-pcb

      - name: Build PlatformIO Project (esp32-breadboard)
        run: pio run -e esp32-breadboard
